import Head from 'next/head'
import {BsFillMoonStarsFill, BsFillBrightnessHighFill, BsLinkedin, BsGithub} from 'react-icons/bs' ;
import {FaDev} from 'react-icons/fa';
import Link from 'next/link';
import { useState , useEffect} from 'react';
import Splash from "./components/Splash";
import { motion } from "framer-motion";


export default function Home() {
  const container = {
    hidden: { opacity: 0 },
    show: {
        opacity:1,
        transition: {
            delayChildren: 0.5,
            staggerChildren: 0.2,
        },
    }
}

const item = {
  hidden:{ y: '100%'},
  show: { y: '0%', transition: { duration:0.5 }},
}

  const [darkMode, setDarkMode] = useState(false);

  const [loading, setLoading] = useState(true)

  useEffect(() => {
    const timer = setTimeout(() => {
      setLoading(false)
    }, 3000)

    return () => clearTimeout(timer)
  }, [])

  return (
    <div className={darkMode ? 'dark' : ''}>
      <Head>
        <title>CP</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico'/>
      </Head>
      {loading ? (
        <Splash />
      ) : (
        <motion.main 
          className=' min-h-screen p-10 font-gloock dark:bg-black'
          initial={{ opacity:0 }}
          animate={{ opacity: 1}}
          transition={{ duration: 0.75, ease: "easeOut"}}
          exit={{ opacity: 1 }}
        >
            <nav className='text-2xl  flex justify-between'>
              <Link href="/">
                <div className='text-2xl '>CP</div>
              </Link>
              <ul className='flex items-center px-10'>
                <li className=' px-2 pr-10 '> 
                  {darkMode ? <BsFillBrightnessHighFill 
                    className='cursor-pointer'
                    onClick={() => setDarkMode(!darkMode)}/> : 
                    <BsFillMoonStarsFill 
                    className='cursor-pointer'
                    onClick={() => setDarkMode(darkMode => !darkMode)}
                  />}
                </li>
                <li className=' px-2'>
                  <Link href='./components/Projects'>Projects</Link>
                  </li>
                <li className=' px-2'>
                  <a href="https://docs.google.com/document/d/1gd_s5Lm468wk0DONMSpgxVsJarLlb9Cx51AHrZmtRnQ/edit?usp=sharing" 
                    target='_blank'
                    rel="noopener noreferrer">
                    Resume
                  </a>
                </li>
              </ul>
            </nav>
            {/* End of Nav */}

            {/* content */}
            <div className=' overflow-hidden mt-64 p-1 text-center  lg:ml-20 lg:mr-64 lg:pr-96 lg:text-left '>
              <div>
              <motion.h1 
                className=' text-6xl py-2'
                animate={{ y:0 }}
                initial={{ y: "100% "}}
                transition={{ delay:0.5, duration:0.5 }}
                >Welcome.
              </motion.h1>
              </div>
      
              <div className=' border-4 lg:border-l-teal-900 border-r-0 border-t-0 border-b-0 lg:pl-5 lg:-ml-3'>
              <h2 className=' text-md py-2 leading-2'>
                  My name is Chantae Palacio. I am a Front End Developer based in Los Angeles, CA. I began my coding journey in 2020.
                  Although it was not &quot;love at first sight&quot; when learning about web development, I eventually grew into loving what I do.
              </h2>
              <h2 className='text-md py-2 leading-2'>
                  I enjoy looking for new ways to express my creativity through building front end projects. For instance, to build my portfolio
                  I used Next.js, TailwindCSS and Framer Motion.
              </h2>
              </div>
            </div>
            <div className='text-center underline text-2xl lg:px-36  lg:text-right lg:flex-col lg:justify-end lg:-mt-44'>
                  <h3 className='text-3xl'>Socials</h3>
                  <motion.ul 
                  variants={container}
                  initial='hidden'
                  animate='show'>
                    <div className='overflow-hidden'>
                      <motion.li 
                      variants={item}
                      className='pb-2 decoration-emerald-100'>Github</motion.li>
                    </div>
                    <div className='overflow-hidden'>
                      <motion.li 
                      variants={item}
                      className='pb-2 decoration-emerald-100'>LinkedIn</motion.li>
                    </div>
                    <div className='overflow-hidden'>
                      <motion.li 
                      variants={item}
                      className='pb-2  decoration-emerald-100'>Dev.to</motion.li>
                    </div>
                  </motion.ul>
            </div>
        </motion.main>
      // End of main Content
      )}
   </div>
  );
}
